"""create deployments table

Revision ID: a192d74afed6
Revises:
Create Date: 2025-11-17 21:16:04.369277

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "a192d74afed6"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
